name: Cush Collective
favicon: null
layout_spectrum: 0.6163478910457343
typography_spectrum: 0.90191
title: Cush Collective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030102'
    - '#675851'
    - '#b4bcc9'
    - '#f50405'
    - '#920109'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.6511861439794302
  rhythmicContrast: 0.25
purpose: []
