name: Cush Collective
favicon: null
layout_spectrum: 0.6163478910457343
typography_spectrum: 0.303702738834545
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6029940857551992
  lightness: 0.366863684495911
  saturation: 0.6511861439794302
  rhythmicContrast: 0.18901257263496518
purpose: []
