typography_spectrum: 0.90191
color:
  brandColors:
    - '#030102'
    - '#675851'
    - '#b4bcc9'
    - '#f50405'
    - '#920109'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.6511861439794302
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6163478910457343
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Andy Yee
  email: sales@cushcollective.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d8da7893-f1f4-48b7-b86c-a279787fae71.jpg
name: Cush Collective
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Quality Bicycle Accessories
purpose: []
